STOP_WORDS = {
    "the", "a", "an", "and", "or", "but", "if", "then", "else", "when",
    "at", "by", "for", "with", "about", "against", "between", "into",
    "through", "during", "before", "after", "above", "below", "to",
    "from", "up", "down", "in", "out", "on", "off", "over", "under",
    "again", "further", "once", "here", "there", "all", "any", "both",
    "each", "few", "more", "most", "other", "some", "such", "only",
    "own", "same", "than", "too", "very", "can", "will", "just",
    "should", "now", "this", "that", "these", "those", "his", "her",
    "its", "their", "our", "your", "what", "which", "who", "whom",
    "was", "were", "been", "being", "have", "has", "had", "having",
    "does", "did", "doing", "not", "nor", "because", "while", "until",
    "says", "said", "say", "also", "amid", "after", "into", "onto",
    "new", "news", "year", "years", "week", "weeks", "month", "day",
    "today", "yesterday", "amid", "could", "would", "may", "might",
    "one", "two", "three", "first", "second", "last", "many", "much",
    "still", "even", "back", "make", "made", "get", "gets", "getting",
    "like", "way", "well", "world", "people", "report", "reports",
    "according", "including", "including", "part", "since", "among",
}
